export const userSeed = [
    {
    email: "email@email.com",
    auth0ID: "098lkj",
    username: "Big Boy Brasky",
    character_name:"veggie guy",
    character_image: "",
    challenged: false,
    currentChallenge: null,
    currenthealth: 100,
    currentoffense: 100,
    currentdefense:100,
    win: 2,
    loss: 3,
    tie: 4,
    level: 1


},
{
    email: "notemail@notemail.com",
    auth0ID: "mqt375",
    username: "Church Lady Rocks",
    character_name:"broccolitti",
    character_image: "",
    challenged: true,
    currentChallenge: "1",
    currenthealth: 110,
    currentoffense: 110,
    currentdefense:130,
    win: 3,
    loss: 3,
    tie: 1,
    level: 1
},
{
    email: "VanByTheRiver@anotheremail.com",
    auth0ID: "321cba",
    username: "Government Cheez",
    character_name:"Frank",
    character_image: "",
    challenged: false,
    currentChallenge: null,
    currenthealth: 150,
    currentoffense: 103,
    currentdefense:180,
    win: 4,
    loss: 2,
    tie: 1,
    level: 1
},
{
    email: "ZepplinRocks@email.com",
    auth0ID: "574shg",
    username: "Pearl4Lyfe",
    character_name:"sick potato",
    character_image: "",
    challenged: true,
    currentChallenge: "1",
    currenthealth: 140,
    currentoffense: 200,
    currentdefense:140,
    win: 5,
    loss: 3,
    tie: 2,
    level: 1
},
{
    email: "superstar@email.com",
    auth0ID: "luv486",
    username: "Ima Superstar",
    character_name:"big pun",
    character_image: "",
    challenged: false,
    currentChallenge: null,
    currenthealth: 145,
    currentoffense: 120,
    currentdefense:160,
    win: 3,
    loss: 4,
    tie: 1,
    level: 1
}
]