export const newVeggieSeed = [
    "Acorn Squash",
    "Ahipa",
    "Amaranth",
    "American Groundnut",
    "Aonori",
    "Arame",
    "Arracacha",
    "Arrowroot",
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Adzuki Bean",
    "Bamboo Shoots",
    "Banana Squash",
    "Beetroot",
    "Belgian Endive",
    "Bell Peppers",
    "Black Eyed Pea",
    "Black Radish",
    "Black Salsify",
    "Bok Choy",
    "Broadleaf Arrowhead",
    "Broccoflower",
    "Broccoli",
    "Broccolini",
    "Brussel Sprouts",
    "Burdock Roots",
    "Buttercup Squash",
    "Butternut Squash",
    "Cabbage",
    "Cactus",
    "Camas",
    "Canna",
    "Caper",
    "Cardoon",
    "Carrot",
    "Cassava",
    "Catsear",
    "Cauliflower",
    "Celeriac",
    "Celery",
    "Celtuce",
    "Chaya",
    "Chayote Squash",
    "Cherry Tomato",
    "Chick Pea",
    "Chickweed",
    "Chicory",
    "Chives",
    "Chrysanthemum",
    "Collard Greens",
    "Common Beans",
    "Crookneck Squash",
    "Common Purslane",
    "Courgette Flowers",
    "Cress",
    "Cucumbers",
    "Dabberlocks",
    "Daikon",
    "Dandelion",
    "Delicata Squash",
    "Daylily",
    "Dill",
    "Dolichos",
    "Drumstick",
    "Dulse",
    "Earthnut Pea",
    "Eggplant",
    "Elephant Foot Yam",
    "Elephant Garlic",
    "Endive",
    "Ensete",
    "Fat Hen",
    "Fava bean",
    "Fennel",
    "Fiddlehead Green",
    "Florence Fennel",
    "Fluted Pumpkin",
    "Galangal",
    "Garbanzo",
    "Garden Rocket",
    "Garlic",
    "Garlic Chives",
    "Ginger",
    "Golden Samphire",
    "Good King Henry",
    "Greater Plantain",
    "Green Beans",
    "Green Soybeans",
    "Guar",
    "Hamburg Parsley",
    "Hijiki",
    "Horse Gram",
    "Horseradish",
    "Indian Pea",
    "Kale",
    "Kohlrabi",
    "Komatsuna",
    "Kombu", 
    "Kurrat", 
    "Lagos Bologi", 
    "Land Cress", 
    "Laver", 
    "Leek", 
    "Lemongrass", 
    "Lentil", 
    "Lettuce", 
    "Lima Bean", 
    "Lotus Root", 
    "Malabar Spinach", 
    "Mangetout", 
    "Manoa", 
    "Mashua", 
    "Mulukhiyah", 
    "Mizuna", 
    "Morel Mushrooms", 
    "Moth Bean", 
    "Mozuku", 
    "Mung Bean", 
    "Mushrooms", 
    "Mustard Greens", 
    "Napa Cabbage", 
    "New Zealand Spinach", 
    "Nopal",
    "Nori", 
    "Ogonori", 
    "Okra", 
    "Onion", 
    "Orache", 
    "Pak Choy", 
    "Paracress", 
    "Parsnip", 
    "Peas", 
    "Pearl Onion", 
    "Pigeon Pea", 
    "Pignut",
    "Potato", 
    "Prussian Asparagus", 
    "Prairie Turnip", 
    "Pumpkin", 
    "Radicchio", 
    "Radish", 
    "Ramp", 
    "Rapini", 
    "Red Leaf Lettuce", 
    "Ricebean", 
    "Runner Bean", 
    "Rutabaga", 
    "Salad Savoy", 
    "Salsify", 
    "Samphire", 
    "Scorzonera", 
    "Sculpit", 
    "Sea Beet", 
    "Sea Grape", 
    "Sea Kale", 
    "Sea Lettuce", 
    "Shallot", 
    "Sierra Leone Bologi", 
    "Skirret", 
    "Snap Pea", 
    "Snow Pea", 
    "Soko", 
    "Sorrel", 
    "Sour Cabbage", 
    "Soybean", 
    "Spinach", 
    "Spring Onion", 
    "Scallion",
    "Squash Blossoms", 
    "Summer Squash", 
    "Swede", 
    "Sweet Potato", 
    "Taro", 
    "Tarwi", 
    "Tatsoi", 
    "Tepary Bean", 
    "Tigernut", 
    "Tomatillo", 
    "Tomato", 
    "Tree Onion", 
    "Turmeric", 
    "Turnip", 
    "Urad Bean", 
    "Ulluco", 
    "Wasabi", 
    "Water Chestnut", 
    "Water Caltrop", 
    "Water Spinach", 
    "Watercress", 
    "Welsh Onion", 
    "Wheatgrass", 
    "Wild Leek", 
    "Winged Bean", 
    "Winter Squash", 
    "Yam", 
    "Yao Choy", 
    "Yardlong Bean", 
    "Yarrow", 
    "Yuca Root", 
    "Yukon Gold Potatoes", 
    "Zucchini", 
    "Banana",
    "Sweet Potatoes",
    "Oatmeal",
    "Lentils",
    "Avacado",
    "Beans",
    "Nuts",
    "Beets",
    "Blueberries",
    "Onions",
    "Squash"  ,
    "Key Lime",
    "Kiwano",
   "Kiwifruit",
    "Kumquat",
    "Lemon",
    "Lime",
    "Loganberries",
    "Longan",
    "Loquat",
    "Lychee",
    "Mamey Sapote",
    "Mango",
    "Mangosteen",
    "Mandarin Orange",
    "Maradol Papaya",
    "Mediterranean Medlar",
    "Mulberries",
    "Muscadine Grapes",
    "Nectarine",
    "Orange",
    "Papaya",
    "Passion Fruit",
    "Peach",
    "Pear",
    "Persian Melon",
    "Persimmon",
    "Pineapple",
    "Plantain",
    "Plum",
    "Plum, Dried",
    "Pomegranate",
    "Pummelo",
    "Quince",
    "Raisins",
    "Raspberries",
    "Red Banana",
    "Red Currants",
    "Rose Apple",
    "Salmonberry",
    "Sapodilla",
    "Sapote",
    "Sharon Fruit",
    "Soursop",
    "South African Baby Pineapple",
    "Star Fruit",
    "Strawberries",
    "Strawberry Guava",
    "Strawberry Papaya",
    "Sugar Apple",
    "Surinam Cherry",
    "Tangerine",
    "Ugli Fruit",
    "Water Coconut",
    "Watermelon",
    "Wild Blueberries",
    "Apple",
    "Apricots, Fresh",
    "Apricots, Dried",
    "Armenian Cucumber",
    "Asian Pears",
    "Barbados Cherry",
    "Black Crowberry",
    "Black Currants",
    "Blackberries",
    "Blood Orange",
    
    "Boysenberries",
    "Breadfruit",
    "Brown Turkey Fig",
    "Cactus Pear",
    "Canary Melon",
    "Cantaloupe",
    "Cape Gooseberries",
    "Cara Cara Navel Orange",
    "Caribbean June Plum",
    "Carissa",
    "Casaba Melon",
    "Champagne Grapes",
    "Cherimoya",
    "Cherries",
    "Cherries, Sour",
    "Chokecherries",
    "Clementines",
    "Coconut",
    "Concord Grapes",
    "Cotton Candy Grapes",
    "Crab Apples",
    "Cranberries, Fresh",
    "Cranberries, Dried",
    "Crenshaw Melon",
    "Custard Apple",
    "D’Agen Sugar Plum",
    "Dates",
    "Date Plum",
    "Durian",
    "Elderberries",
    "Feijoa",
    "Fig, Fresh",
    "Fig, Dried",
    "Galia Melon",
    "Golden Kiwifruit",
    "Grape Juice",
    "Grapefruit",
    "Grapes",
    "Guava",
    "Honeycrisp Apple",
    "Honeydew Melon",
    "Huckleberries",
    "Jackfruit",
    "Jambolan",
    "Jujube",
    "Kaffir Lime",
    "Aubergine",
    "Alfalfa Sprouts",
    "Azuki Beans",
    "Bean Sprouts",
    "Borlotti Beans",
    "Broad Beans",
    "Kidney Beans",
    "Navy Beans",
    "Peanuts",
    "Pinto Beans",
    "Split Peas",
    "Red Cabbage",
    "Frisee",
    "Chard",
    "Swiss Chard",
    "Rainbow Chard",
    "Nettles",
    "Chili Pepper",
    "Jalapeño",
    "Habanero",
    "Paprika",
    "Rhubarb",
    "Eddoe",
    "Konjac",
    "White Radish",
    "Diakon",
    "Jicama",
    "Jerusalem Artichoke",
    "Sweetcorn",
    "Topinambur",
    "Bitter Melon",
    "Gem Squash",
    "Hubbard Squash",
    "Spaghetti Squash",
    "Tat Soi",
    "Cashews",
    "Pistachios"

]